export const melodySoundsMap: { [key: string]: any } = {
  "2A": require("@/assets/sounds/melody/2A.wav"),
  "2A#": require("@/assets/sounds/melody/2A#.wav"),
  "2B": require("@/assets/sounds/melody/2B.wav"),

  "3C": require("@/assets/sounds/melody/3C.wav"),
  "3C#": require("@/assets/sounds/melody/3C#.wav"),
  "3D": require("@/assets/sounds/melody/3D.wav"),
  "3D#": require("@/assets/sounds/melody/3D#.wav"),
  "3E": require("@/assets/sounds/melody/3E.wav"),
  "3F": require("@/assets/sounds/melody/3F.wav"),
  "3F#": require("@/assets/sounds/melody/3F#.wav"),
  "3G": require("@/assets/sounds/melody/3G.wav"),
  "3G#": require("@/assets/sounds/melody/3G#.wav"),
  "3A": require("@/assets/sounds/melody/3A.wav"),
  "3A#": require("@/assets/sounds/melody/3A#.wav"),
  "3B": require("@/assets/sounds/melody/3B.wav"),

  "4C": require("@/assets/sounds/melody/4C.wav"),
  "4C#": require("@/assets/sounds/melody/4C#.wav"),
  "4D": require("@/assets/sounds/melody/4D.wav"),
  "4D#": require("@/assets/sounds/melody/4D#.wav"),
  "4E": require("@/assets/sounds/melody/4E.wav"),
  "4F": require("@/assets/sounds/melody/4F.wav"),
  "4F#": require("@/assets/sounds/melody/4F#.wav"),
  "4G": require("@/assets/sounds/melody/4G.wav"),
  "4G#": require("@/assets/sounds/melody/4G#.wav"),
  "4A": require("@/assets/sounds/melody/4A.wav"),
  "4A#": require("@/assets/sounds/melody/4A#.wav"),
  "4B": require("@/assets/sounds/melody/4B.wav"),
  "4B#": require("@/assets/sounds/melody/4B#.wav"),

  "5C": require("@/assets/sounds/melody/5C.wav"),
  "5C#": require("@/assets/sounds/melody/5C#.wav"),
  "5D": require("@/assets/sounds/melody/5D.wav"),
};

export const bassSoundsMap: { [key: string]: any } = {
  "0A": require("@/assets/sounds/bass/0A.wav"),
  "0A#": require("@/assets/sounds/bass/0A#.wav"),
  "0B": require("@/assets/sounds/bass/0B.wav"),

  "1C": require("@/assets/sounds/bass/1C.wav"),
  "1C#": require("@/assets/sounds/bass/1C#.wav"),
  "1D": require("@/assets/sounds/bass/1D.wav"),
  "1D#": require("@/assets/sounds/bass/1D#.wav"),
  "1E": require("@/assets/sounds/bass/1E.wav"),
  "1F": require("@/assets/sounds/bass/1F.wav"),
  "1F#": require("@/assets/sounds/bass/1F#.wav"),
  "1G": require("@/assets/sounds/bass/1G.wav"),
  "1G#": require("@/assets/sounds/bass/1G#.wav"),
  "1A": require("@/assets/sounds/bass/1A.wav"),
  "1A#": require("@/assets/sounds/bass/1A#.wav"),
  "1B": require("@/assets/sounds/bass/1B.wav"),

  "2C": require("@/assets/sounds/bass/2C.wav"),
  "2C#": require("@/assets/sounds/bass/2C#.wav"),
  "2D": require("@/assets/sounds/bass/2D.wav"),
  "2D#": require("@/assets/sounds/bass/2D#.wav"),
  "2E": require("@/assets/sounds/bass/2E.wav"),
  "2F": require("@/assets/sounds/bass/2F.wav"),
  "2F#": require("@/assets/sounds/bass/2F#.wav"),
  "2G": require("@/assets/sounds/bass/2G.wav"),
  "2G#": require("@/assets/sounds/bass/2G#.wav"),
  "2A": require("@/assets/sounds/bass/2A.wav"),
  "2A#": require("@/assets/sounds/bass/2A#.wav"),
  "2B": require("@/assets/sounds/bass/2B.wav"),

  "3C": require("@/assets/sounds/bass/3C.wav"),
  "3C#": require("@/assets/sounds/bass/3C#.wav"),
  "3D": require("@/assets/sounds/bass/3D.wav"),
};

export const dramSoundsMap: { [key: string]: any } = {
  "bass-drum": require("@/assets/sounds/dram/bass-drum.wav"),
  clash: require("@/assets/sounds/dram/clash.wav"),
  "closed-hihat": require("@/assets/sounds/dram/closed-hihat.wav"),
  "hand-clap": require("@/assets/sounds/dram/hand-clap.wav"),
  "high-tom": require("@/assets/sounds/dram/high-tom.wav"),
  "low-tom": require("@/assets/sounds/dram/low-tom.wav"),
  "open-hihat": require("@/assets/sounds/dram/open-hihat.wav"),
  "pedal-hihat": require("@/assets/sounds/dram/pedal-hihat.wav"),
  ride: require("@/assets/sounds/dram/ride.wav"),
  snare: require("@/assets/sounds/dram/snare.wav"),
};
